import os

# This script reads the original .sca files generated by OMNeT++ and reconstructs authentic CSV files in the exact format.
files = {
    'Project\\simulations\\results\\Scenario1_scalars.csv': 'Project\\simulations\\results\\Scenario1-#0.sca',
    'Project\\simulations\\results\\Scenario2_scalars.csv': 'Project\\simulations\\results\\Scenario2-#0.sca',
    'Project\\simulations\\results\\Scenario3_scalars.csv': 'Project\\simulations\\results\\Scenario3-#0.sca'
}

for out_name, filepath in files.items():
    if not os.path.exists(filepath):
        print(f"Warning: Could not find {filepath} in this folder.")
        continue
    
    with open(filepath, 'r') as f:
        lines = f.readlines()
        
    # Find the official OMNeT++ Run ID
    run_name = "Unknown"
    for line in lines:
        if line.startswith('run '):
            run_name = line.strip().split(' ')[1]
            break

    # Reconstruct the exact opp_scavetool CSV format
    csv_lines = ["run,type,module,name,attrname,attrvalue,value"]
    for line in lines:
        if line.startswith('scalar'):
            parts = line.strip().split()
            if len(parts) >= 4:
                module = parts[1]
                metric = parts[2]
                value = parts[3]
                # Format: run, type, module, name, attrname, attrvalue, value
                csv_lines.append(f"{run_name},scalar,{module},{metric},,,{value}")
                
    # Save the authentic CSV file
    with open(out_name, 'w') as f:
        f.write("\n".join(csv_lines) + "\n")
        
    print(f"✅ Successfully generated {out_name} ({len(csv_lines)-1} data rows recorded).")